theme: jekyll-theme-slate
title: BCS Itera
description: Extensions for Microsoft Dynamics 365 Business Central

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://..."
